// @ts-expect-error — pre-bundled deps, no types; see scripts/bundle-dependencies.mjs
import { ts, typiaTransform } from '../dist/deps.bundle.mjs';
// @ts-expect-error — pre-bundled TS lib files as text, generated by bundle-dependencies.mjs
import { TS_LIB_FILES } from '../dist/ts-lib-files.mjs';
import {
  INLINED_VALIDATE_REPORT,
  INLINED_CREATE_STANDARD_SCHEMA,
  INLINED_ACCESS_EXPRESSION_AS_STRING,
} from './typia-runtime-helpers';
import { extractTypeMetadata, type TypeMetadata } from './extract-type-metadata';

/**
 * Minimal typia `.d.ts` shim. Enough surface area for
 * `typia.createValidate<T>()` to type-check so typia's transformer will match
 * the call and rewrite it. The emitted JS never references typia at runtime —
 * the transformer inlines the validator body in place of the call.
 *
 * Phase 5 replaces this with a more complete stub (covers all the tag types
 * users can attach to fields). For Phase 1 spike, createValidate is enough.
 */
const TYPIA_DTS_STUB = `
declare module "typia" {
  export interface IValidationError { path: string; expected: string; value: unknown; description?: string; }
  export type IValidation<T> =
    | { success: true; data: T }
    | { success: false; data: unknown; errors: IValidationError[] };
  namespace typia {
    function createValidate(): never;
    function createValidate<T>(): (input: unknown) => IValidation<T>;
  }
  export default typia;
}
`;

/**
 * Fallback lib stub — only used if `TS_LIB_FILES` doesn't load. In normal
 * operation the compile function serves typia the real `typescript/lib/lib.*.d.ts`
 * files via TS_LIB_FILES so `checker.isArrayType()` works correctly.
 */
const LIB_DTS_FALLBACK = `
interface Boolean {}
interface Number { toFixed(fractionDigits?: number): string; toString(): string; }
interface String { readonly length: number; charAt(pos: number): string; toString(): string; }
interface Object { toString(): string; hasOwnProperty(v: PropertyKey): boolean; }
interface Function { readonly length: number; readonly name: string; }
interface RegExp { test(s: string): boolean; }
interface IArguments { [index: number]: any; length: number; }
interface CallableFunction extends Function {}
interface NewableFunction extends Function {}
type PropertyKey = string | number | symbol;

interface Array<T> {
  length: number;
  [n: number]: T;
  toString(): string;
  pop(): T | undefined;
  push(...items: T[]): number;
  concat(...items: ConcatArray<T>[]): T[];
  join(separator?: string): string;
  slice(start?: number, end?: number): T[];
  indexOf(searchElement: T, fromIndex?: number): number;
  lastIndexOf(searchElement: T, fromIndex?: number): number;
  every<S extends T>(predicate: (value: T, index: number, array: T[]) => value is S): this is S[];
  every(predicate: (value: T, index: number, array: T[]) => unknown): boolean;
  some(predicate: (value: T, index: number, array: T[]) => unknown): boolean;
  forEach(callbackfn: (value: T, index: number, array: T[]) => void): void;
  map<U>(callbackfn: (value: T, index: number, array: T[]) => U): U[];
  filter<S extends T>(predicate: (value: T, index: number, array: T[]) => value is S): S[];
  filter(predicate: (value: T, index: number, array: T[]) => unknown): T[];
  reduce(callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: T[]) => T): T;
  reduce<U>(callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: T[]) => U, initialValue: U): U;
}
interface ConcatArray<T> { readonly length: number; readonly [n: number]: T; join(separator?: string): string; slice(start?: number, end?: number): T[]; }
interface ReadonlyArray<T> {
  readonly length: number;
  readonly [n: number]: T;
  toString(): string;
  concat(...items: ConcatArray<T>[]): T[];
  join(separator?: string): string;
  slice(start?: number, end?: number): T[];
  indexOf(searchElement: T, fromIndex?: number): number;
  lastIndexOf(searchElement: T, fromIndex?: number): number;
  every(predicate: (value: T, index: number, array: readonly T[]) => unknown): boolean;
  some(predicate: (value: T, index: number, array: readonly T[]) => unknown): boolean;
  forEach(callbackfn: (value: T, index: number, array: readonly T[]) => void): void;
  map<U>(callbackfn: (value: T, index: number, array: readonly T[]) => U): U[];
}
interface ArrayConstructor {
  new(arrayLength?: number): any[];
  new <T>(arrayLength: number): T[];
  new <T>(...items: T[]): T[];
  (arrayLength?: number): any[];
  <T>(arrayLength: number): T[];
  <T>(...items: T[]): T[];
  isArray(arg: any): arg is any[];
  readonly prototype: any[];
}
declare var Array: ArrayConstructor;

interface Promise<T> { then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): Promise<TResult1 | TResult2>; }
interface PromiseLike<T> { then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): PromiseLike<TResult1 | TResult2>; }
interface Date { getTime(): number; toISOString(): string; }
interface DateConstructor { new(): Date; new(value: number | string): Date; now(): number; readonly prototype: Date; }
declare var Date: DateConstructor;

interface Map<K, V> { readonly size: number; get(key: K): V | undefined; has(key: K): boolean; set(key: K, value: V): this; entries(): IterableIterator<[K, V]>; keys(): IterableIterator<K>; values(): IterableIterator<V>; }
interface MapConstructor { new <K, V>(entries?: readonly (readonly [K, V])[] | null): Map<K, V>; readonly prototype: Map<any, any>; }
declare var Map: MapConstructor;
interface Set<T> { readonly size: number; add(value: T): this; has(value: T): boolean; values(): IterableIterator<T>; }
interface SetConstructor { new <T>(values?: readonly T[] | null): Set<T>; readonly prototype: Set<any>; }
declare var Set: SetConstructor;

interface Iterator<T> { next(): { value: T; done?: false } | { value: any; done: true }; }
interface IterableIterator<T> extends Iterator<T> { [Symbol.iterator](): IterableIterator<T>; }
interface Iterable<T> { [Symbol.iterator](): Iterator<T>; }
interface SymbolConstructor { readonly iterator: unique symbol; readonly asyncIterator: unique symbol; }
declare var Symbol: SymbolConstructor;

declare type Partial<T> = { [P in keyof T]?: T[P]; };
declare type Required<T> = { [P in keyof T]-?: T[P]; };
declare type Readonly<T> = { readonly [P in keyof T]: T[P]; };
declare type Record<K extends string | number | symbol, V> = { [P in K]: V; };
declare type Pick<T, K extends keyof T> = { [P in K]: T[P]; };
declare type Exclude<T, U> = T extends U ? never : T;
declare type Omit<T, K extends string | number | symbol> = Pick<T, Exclude<keyof T, K>>;
declare type Extract<T, U> = T extends U ? T : never;
declare type NonNullable<T> = T extends null | undefined ? never : T;
`;


type VirtualFiles = Map<string, string>;

function createVirtualHost(
  files: VirtualFiles,
  target: number,
  defaultLib: string,
): unknown {
  // Normalise candidate path → one of the forms our files map uses. Needed
  // because TypeScript asks for lib files via several path shapes (with or
  // without leading slash, with or without `/lib/` prefix depending on how
  // `getDefaultLibLocation` is plumbed).
  const resolve = (fileName: string): string | undefined => {
    if (files.has(fileName)) return fileName;
    if (files.has('/' + fileName)) return '/' + fileName;
    const base = fileName.split('/').pop()!;
    if (files.has('/' + base)) return '/' + base;
    return undefined;
  };
  return {
    getSourceFile(fileName: string, languageVersion: number) {
      const key = resolve(fileName);
      if (!key) return undefined;
      const content = files.get(key);
      if (content === undefined) return undefined;
      return (ts as { createSourceFile: Function }).createSourceFile(
        fileName,
        content,
        languageVersion,
        true,
      );
    },
    getDefaultLibFileName: () => defaultLib,
    getDefaultLibLocation: () => '/',
    writeFile: () => {},
    getCurrentDirectory: () => '/',
    useCaseSensitiveFileNames: () => true,
    getCanonicalFileName: (f: string) => f,
    getNewLine: () => '\n',
    fileExists: (f: string) => resolve(f) !== undefined,
    readFile: (f: string) => {
      const key = resolve(f);
      return key ? files.get(key) : undefined;
    },
    directoryExists: () => true,
    getDirectories: () => [],
  };
  void target;
}

/**
 * Generate a JS module source string (for a DO facet to load) from a string of
 * TypeScript interface definitions.
 *
 * The emitted module exports a `ParserValidator` class extending `DurableObject`
 * (Cloudflare docs require this shape for `worker.getDurableObjectClass()`).
 * Its `parse(value, typeName)` method dispatches to the typia-generated
 * validator for that type.
 *
 * For each top-level interface `Foo` in `typeDefinitions`, a call to
 * `typia.createValidate<Foo>()` is synthesised. Typia's transformer rewrites
 * the call at emit time, inlining the generated validator body. The emitted
 * JS therefore has no runtime dependency on the typia package.
 *
 * Both `ts` and `typiaTransform` come from the same pre-bundled file so that
 * typia's internal `instanceof ts.Node` checks don't misfire against a second
 * TS instance.
 */
export function generateParseModule(typeDefinitions: string): string {
  // Pass 1: AST walk — collect interface names, `@default` tags, and the
  // type-graph (which fields are typed as named interfaces in this module,
  // and what the target type is). Used by the runtime filler to recurse into
  // nested objects when applying defaults. The extractor enforces Phase 4
  // P4.2: `@default` on a required field throws.
  const metadata: TypeMetadata = extractTypeMetadata(typeDefinitions);
  const { interfaceNames, defaults, relationships: typeGraph } = metadata;

  if (interfaceNames.length === 0) {
    throw new Error('generateParseModule: no interfaces found in typeDefinitions');
  }

  // Pass 2: feed typia the types as written. Named-interface fields validate
  // as embedded objects — no write-shape rewriting in this package (Phase 6.5).
  // Callers that want reference-semantics (ORM write path) pre-extract via
  // `extractTypeMetadata()` and pass `writeShapeTypeDefinitions` themselves.
  const validatorEntries = interfaceNames
    .map((n) => `  ${n}: typia.createValidate<${n}>()`)
    .join(',\n');
  const source = `
import typia from "typia";
${typeDefinitions}

export const validators = {
${validatorEntries}
};
`;

  const tsApi = ts as {
    ScriptTarget: { ESNext: number };
    ModuleKind: { ESNext: number };
    createProgram: Function;
    getPreEmitDiagnostics: Function;
    flattenDiagnosticMessageText: Function;
  };

  // Typia's transformer identifies its calls by checking the resolved
  // declaration's source file path — it looks for substring `typia/lib/<fn>.d.ts`
  // (see @typia/transform CallExpressionTransformer.isTarget). So we host
  // our stub at that path and wire `paths` so `import typia from "typia"`
  // resolves to it. The file *content* is our minimal stub — typia's
  // transformer only cares about the file *path*, not what's inside.
  //
  // The TS lib files come from the real `typescript/lib/lib.*.d.ts` bundled
  // at build time so that `checker.isArrayType()` correctly classifies
  // `T[]` (otherwise typia emits `expected: "{}"` for bare arrays).
  const files: VirtualFiles = new Map();
  const libFiles = (TS_LIB_FILES ?? {}) as Record<string, string>;
  if (libFiles['lib.es2022.d.ts']) {
    for (const [name, content] of Object.entries(libFiles)) {
      files.set('/' + name, content);
    }
  } else {
    files.set('/lib.d.ts', LIB_DTS_FALLBACK);
  }
  files.set('/typia/lib/module.d.ts', TYPIA_DTS_STUB);
  files.set('/input.ts', source);

  const defaultLib = libFiles['lib.es2022.d.ts'] ? 'lib.es2022.d.ts' : 'lib.d.ts';

  const host = createVirtualHost(files, tsApi.ScriptTarget.ESNext, defaultLib);
  const program = tsApi.createProgram(['/input.ts'], {
    strict: true,
    target: tsApi.ScriptTarget.ESNext,
    module: tsApi.ModuleKind.ESNext,
    skipLibCheck: true,
    noEmitOnError: false,
    moduleResolution: 2, // NodeJs
    baseUrl: '/',
    paths: { typia: ['typia/lib/module'] },
  }, host);

  // Typia's transformer factory expects (program, options, extras).
  // `extras` carries diagnostic utilities; supply enough to keep it happy.
  const extras = {
    addDiagnostic: (_diag: unknown) => {},
  };
  const factory = (typiaTransform as Function)(program, undefined, extras);

  let emittedJs: string | null = null;
  const writeFile = (fileName: string, text: string) => {
    if (fileName.endsWith('.js')) emittedJs = text;
  };
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const emitResult = (program as any).emit(
    undefined,
    writeFile,
    undefined,
    false,
    { before: [factory] },
  );

  // Surface fatal diagnostics (user-visible errors during compile).
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const diagnostics = (tsApi.getPreEmitDiagnostics(program) as any[]).concat(emitResult.diagnostics);
  const fatal = diagnostics.filter((d) => d.category === 1 /* Error */);
  if (fatal.length > 0 && !emittedJs) {
    const msgs = fatal
      .slice(0, 3)
      .map((d) => tsApi.flattenDiagnosticMessageText(d.messageText, '\n'))
      .join('\n');
    throw new Error(`generateParseModule: compile errors:\n${msgs}`);
  }

  if (!emittedJs) {
    throw new Error('generateParseModule: no JS was emitted');
  }

  // Typia's emitted JS references `typia/lib/internal/*` helpers plus carries
  // a now-unused `import typia from "typia"`. Rewrite to make the module
  // self-contained — no runtime dependency on any typia package.
  let rewritten: string = emittedJs;
  rewritten = rewritten
    .replace(
      /^import \* as __typia_transform__validateReport from "typia\/lib\/internal\/_validateReport";?$/m,
      INLINED_VALIDATE_REPORT,
    )
    .replace(
      /^import \* as __typia_transform__createStandardSchema from "typia\/lib\/internal\/_createStandardSchema";?$/m,
      INLINED_CREATE_STANDARD_SCHEMA,
    )
    .replace(
      /^import \* as __typia_transform__accessExpressionAsString from "typia\/lib\/internal\/_accessExpressionAsString";?$/m,
      INLINED_ACCESS_EXPRESSION_AS_STRING,
    )
    .replace(/^import typia from "typia";?$/m, '');

  // Guard: refuse to emit if any typia/ import survived the rewrite. Surfaces
  // new helpers typia introduced (upgrade) before they cause facet-load failures.
  const survivingTypiaImport = /import[^;]*from\s+["']typia(?:\/|["'])/;
  if (survivingTypiaImport.test(rewritten)) {
    const line = rewritten.split('\n').find((l) => survivingTypiaImport.test(l)) ?? '';
    throw new Error(
      `generateParseModule: emitted JS still imports from typia — helper inlining needs extending.\nOffending line: ${line}`,
    );
  }
  emittedJs = rewritten;

  // Wrap the emitted JS (which defines `validators = {...}`) in a DO class.
  // The emitted source declares `validators` at top level; we rely on it being
  // hoisted to module scope so the class body can close over it.
  //
  // `__typeMetadata` is module-private: `defaults` for fill-on-parse, and
  // `typeGraph` (which fields reference other named interfaces) so the filler
  // can recurse into nested objects and apply their defaults. No method
  // exposes either — callers that need type-graph introspection use the
  // package's public `extractTypeMetadata()` instead (Phase 6.5 D6.5.4).
  const defaultsJson = JSON.stringify(defaults);
  const typeGraphJson = JSON.stringify(typeGraph);
  return `
import { DurableObject } from "cloudflare:workers";

${emittedJs}

const __typeMetadata = {
  defaults: ${defaultsJson},
  typeGraph: ${typeGraphJson},
};

/**
 * Deep-clone helper used by the filler. We only touch plain objects and
 * arrays; other types (Date, Map, Set, etc.) are passed through by reference.
 * A WeakMap tracks visited nodes so cyclic structures don't blow the stack.
 */
function __clonePlain(v, seen) {
  if (v === null || typeof v !== 'object') return v;
  if (seen.has(v)) return seen.get(v);
  if (Array.isArray(v)) {
    const out = [];
    seen.set(v, out);
    for (let i = 0; i < v.length; i++) out[i] = __clonePlain(v[i], seen);
    return out;
  }
  if (Object.getPrototypeOf(v) === Object.prototype || Object.getPrototypeOf(v) === null) {
    const out = {};
    seen.set(v, out);
    for (const k of Object.keys(v)) out[k] = __clonePlain(v[k], seen);
    return out;
  }
  // Date, Map, Set, RegExp, TypedArrays, class instances — passed through
  // by reference. Safe because the filler never mutates them.
  return v;
}

/**
 * Apply @default values to \`value\` against type \`typeName\`.
 *
 * Non-destructive: returns a new object (plain branches are cloned; other
 * types pass through). A missing property OR an explicit \`undefined\` is
 * replaced by the default; any other value (including \`null\`) is kept.
 *
 * Recurses through fields whose declared type is another named interface in
 * this module, so a sub-interface's \`@default\` tags apply to nested payloads.
 * Cycle-safe via the \`seen\` WeakMap threaded through the walk.
 */
function __fillDefaults(value, typeName, seen) {
  if (value === null || typeof value !== 'object' || Array.isArray(value)) return value;
  if (!seen) seen = new WeakMap();
  if (seen.has(value)) return seen.get(value);

  const typeDefaults = __typeMetadata.defaults[typeName];
  const sub = __typeMetadata.typeGraph[typeName];
  const out = {};
  seen.set(value, out);
  // Clone each field with a FRESH WeakMap — the fill-level \`seen\` tracks
  // "original → filled" for cycle detection across fill recursion, which is
  // a separate concern from the cloner's within-subtree cycle tracking.
  // Sharing one map caused named-interface sub-objects to be seen-marked by
  // the cloner, which then short-circuited the fill recursion and skipped
  // nested defaults.
  for (const k of Object.keys(value)) out[k] = __clonePlain(value[k], new WeakMap());

  if (typeDefaults) {
    for (const field of Object.keys(typeDefaults)) {
      if (out[field] === undefined) {
        out[field] = __clonePlain(typeDefaults[field], new WeakMap());
      }
    }
  }

  // Type-graph recursion uses the ORIGINAL field value (\`value[field]\`),
  // not the cloned (\`out[field]\`), so the \`seen\` WeakMap's "original → clone"
  // mapping catches cycles correctly on re-entry.
  if (sub) {
    for (const field of Object.keys(sub)) {
      const edge = sub[field];
      const origVal = value[field];
      if (origVal === undefined || origVal === null) continue;
      if (edge.cardinality === 'many' && Array.isArray(origVal)) {
        out[field] = origVal.map((elem) =>
          elem && typeof elem === 'object' && !Array.isArray(elem)
            ? __fillDefaults(elem, edge.target, seen)
            : elem,
        );
      } else if (edge.cardinality === 'one' && typeof origVal === 'object' && !Array.isArray(origVal)) {
        out[field] = __fillDefaults(origVal, edge.target, seen);
      }
    }
  }

  return out;
}

export class ParserValidator extends DurableObject {
  parse(value, typeName) {
    const v = validators[typeName];
    if (!v) {
      return {
        valid: false,
        errors: [{ path: "$", expected: typeName, value, description: "unknown type" }],
      };
    }
    const filled = __fillDefaults(value, typeName);
    const result = v(filled);
    if (result.success) return { valid: true, data: result.data };
    return { valid: false, errors: result.errors };
  }
}
`;
}
