// @ts-expect-error — pre-bundled deps, no types; see scripts/bundle-tsc.mjs
import { ts } from '../dist/deps.bundle.mjs';
// @ts-expect-error — pre-bundled TS lib files as text, generated by bundle-tsc.mjs
import { TS_LIB_FILES } from '../dist/ts-lib-files.mjs';

/**
 * The in-memory CompilerHost + `getPreEmitDiagnostics` engine shared by every
 * in-Worker type-check: the ontology validator compile ({@link generateParseModule})
 * AND the codegen loop's SFC semantic gate (apps/nebula). It runs the bundled
 * `typescript` instance inside the DO isolate (no filesystem) — see
 * `scripts/bundle-tsc.mjs` for why `ts` is bundled rather than imported.
 *
 * Extracted from `generate-parse-module.ts` so the SFC gate parameterizes the
 * SAME virtual host (the codegen-loop task's "parameterize the existing
 * createVirtualHost engine", ADR-001 — one TS type-checker, never a second
 * schema language).
 */

type VirtualFiles = Map<string, string>;

/**
 * Minimal CompilerHost backed by an in-memory file map. TypeScript asks for lib
 * files via several path shapes (with/without leading slash, with/without a
 * `/lib/` prefix depending on how `getDefaultLibLocation` is plumbed), so
 * `resolve` normalizes a candidate path to one of the keys our map actually uses.
 */
export function createVirtualHost(files: VirtualFiles, defaultLib: string): unknown {
  const resolve = (fileName: string): string | undefined => {
    if (files.has(fileName)) return fileName;
    if (files.has('/' + fileName)) return '/' + fileName;
    const base = fileName.split('/').pop()!;
    if (files.has('/' + base)) return '/' + base;
    return undefined;
  };
  return {
    getSourceFile(fileName: string, languageVersion: number) {
      const key = resolve(fileName);
      if (!key) return undefined;
      const content = files.get(key);
      if (content === undefined) return undefined;
      return (ts as { createSourceFile: Function }).createSourceFile(
        fileName,
        content,
        languageVersion,
        true,
      );
    },
    getDefaultLibFileName: () => defaultLib,
    getDefaultLibLocation: () => '/',
    writeFile: () => {},
    getCurrentDirectory: () => '/',
    useCaseSensitiveFileNames: () => true,
    getCanonicalFileName: (f: string) => f,
    getNewLine: () => '\n',
    fileExists: (f: string) => resolve(f) !== undefined,
    readFile: (f: string) => {
      const key = resolve(f);
      return key ? files.get(key) : undefined;
    },
    directoryExists: () => true,
    getDirectories: () => [],
  };
}

/**
 * Seed `files` with the bundled `typescript/lib/lib.*.d.ts` text modules so
 * `checker.isArrayType()` and the DOM/ES globals resolve. Returns the default
 * lib filename to hand the host (`lib.es2022.d.ts` when the real libs loaded;
 * the caller's `lib` compiler option pulls in additional libs like `lib.dom`).
 *
 * When the lib bundle didn't load (`TS_LIB_FILES` empty), there is no DOM/ES
 * surface to fall back to here — callers that need it must supply their own
 * ambient declarations; this returns `'lib.es2022.d.ts'` regardless so the host
 * has a stable default-lib name.
 */
export function seedTsLibFiles(files: VirtualFiles): string {
  const libFiles = (TS_LIB_FILES ?? {}) as Record<string, string>;
  for (const [name, content] of Object.entries(libFiles)) {
    files.set('/' + name, content);
  }
  return 'lib.es2022.d.ts';
}

export interface CheckResult {
  ok: boolean;
  /** Flattened `category: Error` diagnostic messages (empty when `ok`). */
  messages: string[];
}

/**
 * Type-check `rootNames` against `files` + the bundled TS libs and return the
 * fatal (`category: Error`) diagnostics as flat strings. Pure — no emit, no
 * side effects. The SFC semantic gate (apps/nebula codegen loop) feeds the
 * extracted `<script setup>` plus ambient Vue + Nebula-API `.d.ts` files here;
 * a bad union literal (e.g. `op: 'set'`) surfaces as a TS2322/2345 message.
 *
 * `lib` defaults to ES2022 + DOM so realistic browser/Vue script bodies
 * (`document`, `window`, `console`) don't produce spurious unresolved-global
 * errors. Caller-supplied `files` are added on top of the seeded libs.
 */
export function checkTypeScript(opts: {
  files: Record<string, string>;
  rootNames: string[];
  lib?: string[];
}): CheckResult {
  const tsApi = ts as {
    ScriptTarget: { ESNext: number };
    ModuleKind: { ESNext: number };
    createProgram: Function;
    getPreEmitDiagnostics: Function;
    flattenDiagnosticMessageText: Function;
  };
  const files: VirtualFiles = new Map();
  const defaultLib = seedTsLibFiles(files);
  for (const [name, content] of Object.entries(opts.files)) {
    files.set(name.startsWith('/') ? name : '/' + name, content);
  }
  const host = createVirtualHost(files, defaultLib);
  const program = tsApi.createProgram(opts.rootNames, {
    strict: true,
    target: tsApi.ScriptTarget.ESNext,
    module: tsApi.ModuleKind.ESNext,
    moduleResolution: 2, // NodeJs
    skipLibCheck: true,
    noEmit: true,
    noEmitOnError: false,
    baseUrl: '/',
    lib: opts.lib ?? ['lib.es2022.d.ts', 'lib.dom.d.ts'],
  }, host);

  const diagnostics = (tsApi.getPreEmitDiagnostics(program) as Array<{
    category: number;
    messageText: unknown;
  }>).filter((d) => d.category === 1 /* Error */);
  const messages = diagnostics.map((d) =>
    tsApi.flattenDiagnosticMessageText(d.messageText, '\n'),
  );
  return { ok: messages.length === 0, messages };
}
