/**
 * THE HEADLINE (collapse Phase 4) — four parties in ONE thread, live, attributed:
 *
 *  - the OWNER — a real `@lumenize.io` email login (ADR-009 rung 1, `provisionAndLogin`);
 *  - the COACH — a real platform super-admin login (the bootstrap email re-pointed at the
 *    catch-all via `bootVars`), acting in the galaxy under downward dominion;
 *  - the COLLABORATOR (Austen) — enrolled through the REAL invite: a galaxy node invite
 *    with one `write` grant at the chat node, NO galaxy `scopeAdmin` bit, and the
 *    workspace SECOND HALF (a co-minted `.dev` scopeAdmin membership whose session the
 *    SAME acceptance click seeded — asserted here by her actually READING `.dev` data);
 *  - NEBULA — the agent, whose reply is generated by the REAL model (the REST lane),
 *    triggered by the COLLABORATOR's committed message (the DAG write is the only door),
 *    attributed `{ sub: Austen, act: { sub: agent:nebula } }` and rendered via its
 *    seeded `Profile` ("Nebula" + avatar).
 *
 * Every party sees every message on the SAME durable `Message` subscription; kinds and
 * subjects are derived from the stamped actingToken, never from the values.
 */
import assert from 'node:assert/strict';
import { DEFAULT_CHAT_ID, CHAT_NODE_ID } from '@lumenize/nebula/client';
import type { Galaxy, Snapshot, NodeInviteAck } from '@lumenize/nebula';
import { deriveKind, deriveParticipants } from '@lumenize/nebula/client';
import { NEBULA_SUB } from '@lumenize/nebula-auth/claims';
import { waitForEmail } from '@lumenize/email-test/client';
import type { DevStack, Driver } from '../lib/harness';
import { connectDriver, readDevVar } from '../lib/harness';
import {
  refreshAccessToken, pointInviteLinkAt, acceptMembership, refreshTokenForScope, setCookieHeaders,
} from '../../test/lib/email-login';

const uniqueTestEmail = () => `test-${crypto.randomUUID().slice(0, 8)}@lumenize.io`;
import { parseJwtUnsafe } from '@lumenize/crypto';

export const needsContainer = false;

/** The bootstrap (coach) email, re-pointed at the catch-all so the login is a REAL loop. */
const COACH_EMAIL = 'coach-four@lumenize.io';
export const bootVars = { NEBULA_AUTH_BOOTSTRAP_EMAIL: COACH_EMAIL };

const SCOPE = 'claude-four.app';
const PLATFORM_SCOPE = 'nebula-platform';
/** A real (REST-lane) generation fits well inside this; silence past it is the failure. */
const REPLY_TIMEOUT_MS = 240_000;

const chatQuery = {
  queryType: 'parentChild' as const, typeName: 'Message', field: 'chat', value: DEFAULT_CHAT_ID,
};

async function waitForReply(driver: Driver, sub: { resourceIds: string[] }, repliedTo: string): Promise<Snapshot> {
  const deadline = Date.now() + REPLY_TIMEOUT_MS;
  for (;;) {
    for (const id of sub.resourceIds) {
      const snap = await driver.client.resources.read('Message', id) as Snapshot | null;
      if (snap && deriveKind(snap.meta.actingToken) === 'agent'
        && (snap.value as { replyTo?: string }).replyTo === repliedTo) return snap;
    }
    assert.ok(Date.now() < deadline,
      `no agent reply to ${repliedTo} within ${REPLY_TIMEOUT_MS / 1000}s — the triggered turn is silent server-side, so this deadline is the loud form of a broken trigger/transport`);
    await new Promise((r) => setTimeout(r, 2000));
  }
}

export async function run(stack: DevStack): Promise<void> {
  const testToken = readDevVar('TEST_TOKEN');
  const origin = stack.baseUrl.replace(/\/$/, '');
  const disposables: Array<{ dispose: () => void }> = [];
  try {
    // ── The OWNER: real email login, real provisioning ──
    const owner = await connectDriver(stack, { scope: SCOPE });
    disposables.push(owner);

    // ── The COACH: a real platform bootstrap login, then acting in the galaxy ──
    // ⚠️ `_scopeless` — the login request below names no scope, so its mail carries no platform tag.
    const coachWaiter = waitForEmail({ testToken, instance: '_scopeless', to: COACH_EMAIL, timeout: 60_000 });
    let coachRefresh: string;
    try {
      await fetch(`${origin}/auth/email-magic-link`, {
        method: 'POST', headers: { 'content-type': 'application/json' },
        body: JSON.stringify({ email: COACH_EMAIL }),
      });
      const { extractMagicLink } = await import('@lumenize/email-test/client');
      const link = extractMagicLink(await coachWaiter.emailPromise);
      const clicked = await fetch(link, { redirect: 'manual' });
      // ⚠️ `headers.get('set-cookie')` returns only the FIRST of N under mint-all — read them all,
      // and pick the one Path-bound to the scope this session refreshes at.
      const found = refreshTokenForScope(setCookieHeaders(clicked), PLATFORM_SCOPE);
      assert.ok(found, `coach bootstrap login set no cookie for "${PLATFORM_SCOPE}" (${clicked.status})`);
      coachRefresh = found;
      // A click is not consent — the cookie is inert until its holder accepts, superuser included.
      await acceptMembership(origin, coachRefresh, PLATFORM_SCOPE);
    } finally {
      coachWaiter.cleanup();
    }
    const coachSession = await refreshAccessToken(
      origin, { refreshToken: coachRefresh, authScope: PLATFORM_SCOPE }, SCOPE, fetch,
    );
    const coach = await connectDriver(stack, {
      scope: SCOPE, session: { accessToken: coachSession.accessToken, sub: coachSession.sub },
    });
    disposables.push(coach);

    // ── The COLLABORATOR: the REAL node invite (write at the chat node, no admin bit) ──
    const austenEmail = uniqueTestEmail();
    const austenWaiter = waitForEmail({ testToken, instance: SCOPE, to: austenEmail, timeout: 60_000 });
    let austenGalaxyToken: string; let austenDevToken: string;
    try {
      const ack = await owner.client.lmz.callAsync('GALAXY', SCOPE,
        owner.client.ctn<Galaxy>().invite(CHAT_NODE_ID, [{ email: austenEmail, tier: 'write' }])) as NodeInviteAck;
      assert.deepEqual(ack, { accepted: 1, errors: [] }, `invite ack: ${JSON.stringify(ack)}`);
      const mail = await austenWaiter.emailPromise;
      const href = /href="([^"]*accept-invite[^"]*invite_token[^"]*)"/.exec(mail.html ?? '')?.[1];
      assert.ok(href, 'invite email carried no accept link');
      const clicked = await fetch(pointInviteLinkAt(origin, href!.replace(/&amp;/g, '&')), { redirect: 'manual' });
      const cookies = clicked.headers.getSetCookie?.() ?? [clicked.headers.get('set-cookie') ?? ''];
      // THE SECOND HALF: one acceptance click seeded BOTH Path-scoped sessions.
      const g = cookies.find((c) => c.includes(`Path=/auth/${SCOPE};`));
      const d = cookies.find((c) => c.includes(`Path=/auth/${SCOPE}.dev;`));
      assert.ok(g, `acceptance set no galaxy cookie (${clicked.status}; ${cookies.length} cookies)`);
      assert.ok(d, 'acceptance set no .dev workspace cookie — the invite second half is missing');
      austenGalaxyToken = /refresh-token=([^;]+)/.exec(g!)![1]!;
      austenDevToken = /refresh-token=([^;]+)/.exec(d!)![1]!;
      // Both cookies are inert until Austen consents, and one act covers both: `acceptMembership`
      // converges the co-minted `.dev` sibling alongside the galaxy membership it is called for —
      // which is why the `.dev` session below works off a single accept.
      await acceptMembership(origin, austenGalaxyToken, SCOPE);
    } finally {
      austenWaiter.cleanup();
    }
    const austenSession = await refreshAccessToken(
      origin, { refreshToken: austenGalaxyToken, authScope: SCOPE }, SCOPE, fetch,
    );
    const austenClaims = parseJwtUnsafe(austenSession.accessToken)!.payload as unknown as { access: { scopeAdmin?: boolean } };
    assert.equal(austenClaims.access.scopeAdmin, undefined, 'Austen must hold NO galaxy admin bit');
    const austen = await connectDriver(stack, {
      scope: SCOPE, session: { accessToken: austenSession.accessToken, sub: austenSession.sub },
    });
    disposables.push(austen);

    // ── Every party subscribes the ONE thread ──
    using ownerSub = owner.client.resources.subscribeQuery(chatQuery); await ownerSub.ready;
    using coachSub = coach.client.resources.subscribeQuery(chatQuery); await coachSub.ready;
    using austenSub = austen.client.resources.subscribeQuery(chatQuery); await austenSub.ready;

    // ── The messages: owner, coach, then AUSTEN — SEQUENTIAL, awaiting each reply.
    // Every human commit triggers a generation and the trigger is SINGLE-FLIGHT (a post
    // during a generation is deliberately skipped — the pre-alpha floor), so the
    // scenario waits out each turn the way a participant would. Verified live: three
    // rapid posts yielded exactly one generation before this was sequenced.
    const ownerMsg = await owner.client.postUserMessage('Welcome to the build thread. Do not change any code yet.');
    await waitForReply(owner, ownerSub, ownerMsg);
    const coachMsg = await coach.client.postUserMessage('Coach here — looks good so far. No code changes needed.');
    await waitForReply(coach, coachSub, coachMsg);
    const austenMsg = await austen.client.postUserMessage(
      'What does this app do so far? Answer briefly - do not change any code.',
    );

    // Nebula replies — triggered by the NON-ADMIN collaborator's write-granted commit.
    const reply = await waitForReply(owner, ownerSub, austenMsg);
    assert.equal(reply.meta.actingToken.sub, austenSession.sub,
      'the reply runs under the TRIGGERING person\'s own authority (the participant model)');
    assert.equal(reply.meta.actingToken.act?.sub, NEBULA_SUB, 'Nebula is the stamped actor');
    const parties = deriveParticipants(reply.meta.actingToken);
    assert.deepEqual(parties.map((p) => p.kind), ['agent', 'human'], 'byline: Nebula for {Austen}');

    // ── ALL FOUR parties visible to ALL THREE humans, attribution derived per message ──
    for (const [who, sub, client] of [
      ['owner', ownerSub, owner] as const, ['coach', coachSub, coach] as const, ['austen', austenSub, austen] as const,
    ]) {
      const deadline = Date.now() + 30_000;
      while (sub.resourceIds.length < 6 && Date.now() < deadline) await new Promise((r) => setTimeout(r, 500));
      for (const [id, expectSub, expectKind] of [
        [ownerMsg, owner.sub, 'human'], [coachMsg, coachSession.sub, 'human'],
        [austenMsg, austenSession.sub, 'human'],
      ] as const) {
        const snap = await client.client.resources.read('Message', id) as Snapshot;
        assert.equal(snap.meta.actingToken.sub, expectSub, `${who} sees ${id} attributed to its sender`);
        assert.equal(deriveKind(snap.meta.actingToken), expectKind, `${who} derives the right kind`);
      }
      assert.ok(sub.resourceIds.length >= 6, `${who} sees the whole thread (${sub.resourceIds.length})`);
    }

    // ── Nebula RENDERS via its seeded Profile ("Nebula" + avatar) ──
    using nebulaProfile = owner.client.subscribeProfile(NEBULA_SUB);
    const prof = await nebulaProfile.snapshot as { value?: { name?: string; picture?: string } } | null;
    assert.equal(prof?.value?.name, 'Nebula', 'the actor resolves through the seeded Nebula Profile');
    assert.ok((prof?.value?.picture ?? '').length > 0, 'the seeded Profile carries the avatar');

    // ── The second half CONSUMED: Austen READS `.dev` Star data on her own dev session ──
    const devSession = await refreshAccessToken(
      origin, { refreshToken: austenDevToken, authScope: `${SCOPE}.dev` }, `${SCOPE}.dev`, fetch,
    );
    const devClaims = parseJwtUnsafe(devSession.accessToken)!.payload as unknown as { access: { authScope: string; scopeAdmin?: boolean } };
    assert.equal(devClaims.access.authScope, `${SCOPE}.dev`, 'her dev session is star-scoped');
    assert.equal(devClaims.access.scopeAdmin, true, 'she holds scopeAdmin over the workspace Star');
    const austenDev = await connectDriver(stack, {
      scope: `${SCOPE}.dev`, session: { accessToken: devSession.accessToken, sub: devSession.sub },
    });
    disposables.push(austenDev);
    // A real read of `.dev` Star data: the org tree (ADR-008 — visible to every member).
    let tree: unknown;
    austenDev.client.onOrgTreeUpdate((state: unknown) => { tree = state; });
    await austenDev.client.lmz.callAsync('STAR', `${SCOPE}.dev`,
      austenDev.client.ctn<{ subscribeTree(): void }>().subscribeTree());
    const treeDeadline = Date.now() + 15_000;
    while (tree === undefined && Date.now() < treeDeadline) await new Promise((r) => setTimeout(r, 250));
    assert.ok(tree !== undefined, 'Austen READ .dev Star data (the org tree arrived on her own dev session)');

    console.error('[four-party-chat] all four parties live + attributed; the reply ran under Austen\'s authority');
  } finally {
    for (const d of disposables) { try { d.dispose(); } catch { /* already */ } }
  }
}
