// Generates src/validator-seeds.ts — the COMMITTED, precompiled validator literals for
// the two constant ontologies the Worker used to compile at runtime: the platform chat
// seed row (CHAT_MESSAGE_TYPES @ CHAT_MESSAGE_ONTOLOGY_VERSION) and the codegen
// tool-args module (TOOL_ARGS_TYPES). Neither input takes user data or varies by
// tenant, so compiling them at runtime bought nothing and held the multi-MB compiler in
// the Worker bundle (tasks/nebula-move-compilers-out-of-the-worker.md). Run
// `npx tsx scripts/gen-validator-seeds.ts` after editing an input; the OUTPUT IS
// COMMITTED. One-shot generator, not a build step — nothing in the dev loop runs it
// (no-build-in-dev); `--check` (wired into the package `test` script ahead of vitest)
// REBUILDS both literals and diffs, so staleness from ANY cause — an input edit, a
// parser-validator bump — fails loudly. A stamp of input versions would go quiet the
// moment an unlisted input changed; rebuilding derives the answer.
// (Pattern: scripts/gen-scaffold.mjs; tsx because the inputs are TS modules.)
//
// ⚠️ A regenerated module is only HALF the change — the BUNDLE ID must move with it.
// `getParserValidatorFacet` caches by id, so a changed module under a reused id serves
// the STALE validator, and nothing catches a stale id the way --check catches a stale
// literal. Concretely:
//   - TOOL_ARGS_VALIDATOR_MODULE changed → bump TOOL_ARGS_BUNDLE_ID
//     (src/tool-args-constants.ts).
//   - CHAT_ONTOLOGY_SEED_ROW changed → bump CHAT_MESSAGE_ONTOLOGY_VERSION
//     (src/chat-constants.ts) — the chat loader id derives from the installed label,
//     and an already-seeded Galaxy keeps serving its installed row regardless.
import { readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { generateParseModule } from '@lumenize/ts-runtime-parser-validator/compile';
import { compileOntologyVersion } from '../src/ontology-compile';
import { CHAT_MESSAGE_ONTOLOGY_VERSION, CHAT_MESSAGE_TYPES } from '../src/chat-constants';
import { TOOL_ARGS_TYPES } from '../src/tool-args-constants';

const here = dirname(fileURLToPath(import.meta.url));
const target = join(here, '..', 'src', 'validator-seeds.ts');

const chatRow = compileOntologyVersion({
  version: CHAT_MESSAGE_ONTOLOGY_VERSION,
  types: CHAT_MESSAGE_TYPES,
});
const toolArgsModule = generateParseModule(TOOL_ARGS_TYPES);

const out = `// GENERATED by scripts/gen-validator-seeds.ts — do not hand-edit; edit the INPUTS
// (src/chat-constants.ts, src/tool-args-constants.ts, or the compiler they feed) and
// re-run \`npx tsx scripts/gen-validator-seeds.ts\`. The package \`test\` script runs
// \`--check\` ahead of vitest, which rebuilds both literals and reds on drift.
//
// ⚠️ A changed literal REQUIRES a bundle-id bump beside it — the Worker Loader caches
// by id, so a changed module under a reused id serves the stale validator. See the
// generator's header for which id pairs with which literal.
import type { OntologyVersionRow } from './ontology-compile';

/**
 * The platform chat ontology's compiled seed row — the FIRST install's content for a
 * Galaxy's chat registry ({@link chatOntologySeedRow} hands it over). Precompiled and
 * committed so no Worker ever runs the ontology compiler for a constant input.
 */
export const CHAT_ONTOLOGY_SEED_ROW: OntologyVersionRow = {
  version: ${JSON.stringify(chatRow.version)},
  types: ${JSON.stringify(chatRow.types)},
  validatorBundle: ${JSON.stringify(chatRow.validatorBundle)},
  relationships: ${JSON.stringify(chatRow.relationships)},
};

/**
 * The codegen tool-args validator module (typia, from \`TOOL_ARGS_TYPES\`) — what
 * \`Galaxy.#ensureToolArgsFacet\` hands the Worker Loader under \`TOOL_ARGS_BUNDLE_ID\`.
 */
export const TOOL_ARGS_VALIDATOR_MODULE: string = ${JSON.stringify(toolArgsModule)};
`;

if (process.argv.includes('--check')) {
  let current: string;
  try {
    current = readFileSync(target, 'utf8');
  } catch {
    console.error('validator-seeds MISSING: run `npx tsx scripts/gen-validator-seeds.ts` and commit src/validator-seeds.ts');
    process.exit(1);
  }
  if (current !== out) {
    console.error('validator-seeds DRIFT: an input changed — run `npx tsx scripts/gen-validator-seeds.ts`, commit src/validator-seeds.ts, and bump the matching bundle id (see the generator header)');
    process.exit(1);
  }
  console.log('validator-seeds in sync');
} else {
  writeFileSync(target, out);
  console.log(`wrote src/validator-seeds.ts — chat row ${chatRow.validatorBundle.length} chars, tool-args ${toolArgsModule.length} chars`);
}
